version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/vendingdb?authSource=admin
      ME_CONFIG_BASICAUTH: false

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - 3080:3080
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://root:example@mongo:27017/vendingdb?authSource=admin
    depends_on:
      - mongo
    # volumes:
    #   - ./public:/app/public # Mount public folder into container
networks:
  default:
    name: app_network
